reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode6.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - DESTINATION="OS=8.3,name=iPhone 6" SCHEME="Auth0-iOS" SDK=iphonesimulator8.4
  - DESTINATION="OS=8.4,name=iPhone 6 Plus" SCHEME="Auth0-iOS" SDK=iphonesimulator8.4
  - DESTINATION="arch=x86_64" SCHEME="Auth0-OSX" SDK=macosx10.10
cache:
  - bundler
before_install:
  - gem install xcpretty --no-ri --no-rdoc
script:
  - 'xcodebuild -project Auth0.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO test | xcpretty -c ; exit ${PIPESTATUS[0]}'
branches:
  only:
  - master